### ISSUE TITLE
The Docker image doesn't run

### ISSUE THREAD

**Issue by domino14** [orktes/go-torch#1]
I get these (and a large number of errors afterwards):

```
17:37 $ docker-compose up test
Creating scripts_test_1 ... done
Attaching to scripts_test_1
test_1       | # github.com/orktes/go-torch
test_1       | torch.cpp: In function 'c10::IValue Torch_ConvertTorchIValueToIValue(Torch_IValue)':
test_1       | torch.cpp:160:28: error: 'torch::jit::Tuple' has not been declared
test_1       |          return torch::jit::Tuple::create(std::move(values));
test_1       |                             ^~~~~
test_1       | torch.cpp: In function 'void* Torch_LoadJITModule(char*, Torch_Error*)':
test_1       | torch.cpp:226:47: error: no match for 'operator=' (operand types are 'std::shared_ptr<torch::jit::script::Module>' and 'torch::jit::script::Module')
test_1       |      mod->module = torch::jit::load(module_path);
```

**Comment by domino14** [comment]
It seems to be because the latest version of pytorch puts `Tuple` in another namespace: `c10::ivalue::Tuple`. Replacing this above, though, shows a litany of other issues; `torch::jit::compile` and `torch::jit::load` now return different types (the former returns a `CompilationUnit`, modules are no longer pointers, etc etc). 

Basically, the torch API changed enough that this binding doesn't work anymore. I'm not sure I know enough to fix it, although I tried for a bit. Is anyone out there willing to keep maintaining this project?

**Comment by orktes** [comment]
Hey! Will try to make time to fix this once I have time. Contributions are also welcome!

**Comment by orktes** [comment]
Locked down torch version (old version). It works now but will look into updating libtorch later. https://github.com/orktes/go-torch/commit/e35d5f06370f566d665536d7a5b9505a4912dc06
