### ISSUE TITLE
torch.cpp:3:10: fatal error: 'torch/torch.h' file not found

### ISSUE THREAD

**Issue by atlantiswqq** [orktes/go-torch#3]
When I use the `go get github.com/orktes/go-torch`command to download the package
return 
`torch.cpp:3:10: fatal error: 'torch/torch.h' file not found`

**Comment by orktes** [comment]
Hey! Will try to make time to fix this once I have time. Contributions are also welcome!

**Comment by orktes** [comment]
Locked down torch version (old version). It works now but will look into updating libtorch later. https://github.com/orktes/go-torch/commit/e35d5f06370f566d665536d7a5b9505a4912dc06

**Comment by Beninington** [comment]
maybe you need add path xxx.\include\torch\csrc\api\include\
