### ISSUE TITLE
Up to date instructions to build the package

### ISSUE THREAD

**Issue by vkuznet** [orktes/go-torch#4]
Hi,
I'm interested to try out this package but I find that build instructions are out of date. I tried to setup docker with recent version of libtorch library https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip or https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.8.1%2Bcpu.zip but go get fails on multiple fronts. For example, the libtorch library has different structure of includes now, e.g. torch/torch.h is hidden within csrc area, etc. Even if I copy everything to /usr/local the go get complains about #error C++14 or later compatible compiler is required to use PyTorch (even though docker has recent g++). There are lots of errors from c10, etc.

I'll appreciate if proper set of instruction how to build torch.cpp (supplied in this package) will be provided in order to build go based code.

**Comment by orktes** [comment]
Hey!

Yeah everything is badly out of date. Everything was done against libtorch 1.0.1 (see https://github.com/orktes/go-torch/blob/master/scripts/Dockerfile). I recommend checking out which seems to be a lot more active https://github.com/wangkuiyi/gotorch.
